# Generated by Django 5.2.4 on 2025-07-05 01:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='unique_id',
            field=models.CharField(default=accounts.models.generate_unique_id, max_length=100),
        ),
    ]
