# Generated by Django 5.2.1 on 2025-07-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_authorized_shares',
            field=models.PositiveIntegerField(default=0, help_text='Total shares that this company can allocate'),
        ),
    ]
