# Generated by Django 5.2.1 on 2025-07-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_total_authorized_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_fmv',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current FMV per share (S)', max_digits=12),
        ),
        migrations.AddField(
            model_name='company',
            name='risk_free_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Risk-free rate (r)', max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='volatility',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Annualized volatility (Sigma)', max_digits=5),
        ),
    ]
