# Generated by Django 5.2.1 on 2025-07-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_current_fmv_company_risk_free_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='current_fmv',
        ),
        migrations.AddField(
            model_name='company',
            name='current_share_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Latest market price per share', max_digits=12),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='risk_free_rate',
            field=models.DecimalField(decimal_places=4, default=0.03, help_text='Annual Rf rate as a decimal (e.g. 0.03)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_authorized_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='volatility',
            field=models.DecimalField(decimal_places=4, default=0.5, help_text='Annual volatility (σ) as a decimal', max_digits=5),
        ),
    ]
