# Generated by Django 5.2.2 on 2025-08-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_company_current_fmv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='current_share_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='company',
            name='risk_free_rate',
            field=models.FloatField(default=0.0, help_text='Annual risk-free rate, e.g. 0.03 for 3%'),
        ),
        migrations.AlterField(
            model_name='company',
            name='volatility',
            field=models.FloatField(default=0.0, help_text='Annualized σ, e.g. 0.25 for 25%'),
        ),
    ]
