# Generated by Django 5.2.4 on 2025-09-05 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_company_current_share_price_and_more'),
        ('accounts', '0006_userprofile_email_verified_and_more'),
    ]

    operations = [
    ]
