# Generated by Django 5.2.4 on 2025-09-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20250905_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_secret',
        ),
    ]
