# Generated by Django 5.2.4 on 2025-09-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_market_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated total company equity value (USD)', max_digits=18),
        ),
        migrations.CreateModel(
            name='CompanyFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='accounts.company')),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('company', 'year'), name='unique_company_year_financial')],
            },
        ),
    ]
