# Generated by Django 5.2.1 on 2025-07-06 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_company_total_authorized_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_class_shares', models.PositiveIntegerField(default=0, help_text='Shares this class may issue')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_classes', to='accounts.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EquityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_shares', models.PositiveIntegerField(help_text='Total shares allocated')),
                ('iso_shares', models.PositiveIntegerField(default=0, help_text='ISO share count')),
                ('nso_shares', models.PositiveIntegerField(default=0, help_text='NSO share count')),
                ('rsu_shares', models.PositiveIntegerField(default=0, help_text='RSU share count')),
                ('strike_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grant_date', models.DateField(default=django.utils.timezone.now)),
                ('vesting_start', models.DateField(blank=True, null=True)),
                ('vesting_end', models.DateField(blank=True, null=True)),
                ('cliff_months', models.PositiveIntegerField(default=0, help_text='Months until first vest (cliff)')),
                ('total_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bso_value_per_option', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('black_scholes_iso_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_grants', to='accounts.userprofile')),
                ('stock_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equity.stockclass')),
            ],
        ),
    ]
