# Generated by Django 5.2.1 on 2025-07-27 21:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_company_current_share_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('share_type', models.CharField(choices=[('preferred', 'Preferred'), ('common', 'Common')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='StockClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_class_shares', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_classes', to='accounts.company')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_classes', to='equity.series')),
            ],
        ),
        migrations.CreateModel(
            name='EquityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_shares', models.PositiveIntegerField()),
                ('iso_shares', models.PositiveIntegerField(default=0)),
                ('nqo_shares', models.PositiveIntegerField(default=0)),
                ('rsu_shares', models.PositiveIntegerField(default=0)),
                ('common_shares', models.PositiveIntegerField(default=0)),
                ('preferred_shares', models.PositiveIntegerField(default=0)),
                ('strike_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Used only for common or preferred shares purchased outright (not options)', max_digits=10, null=True)),
                ('grant_date', models.DateField(default=django.utils.timezone.now)),
                ('vesting_start', models.DateField(blank=True, null=True)),
                ('vesting_end', models.DateField(blank=True, null=True)),
                ('vesting_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('cliff_months', models.PositiveIntegerField(default=0, help_text='Full months since vesting_start (auto-calculated on save)')),
                ('total_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bso_value_per_option', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('black_scholes_iso_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_grants', to='accounts.userprofile')),
                ('stock_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_grants', to='equity.stockclass')),
            ],
        ),
    ]
