# Generated by Django 5.2.1 on 2025-07-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitygrant',
            name='common_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equitygrant',
            name='preferred_shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
