# Generated by Django 5.2.1 on 2025-07-27 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_company_current_share_price_and_more'),
        ('equity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='accounts.company'),
            preserve_default=False,
        ),
    ]
