# Generated by Django 5.2.4 on 2025-10-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='company',
        ),
        migrations.AlterField(
            model_name='series',
            name='share_type',
            field=models.CharField(blank=True, choices=[('COMMON', 'Common'), ('PREFERRED', 'Preferred')], max_length=20, null=True),
        ),
    ]
