# Generated by Django 5.2.4 on 2025-10-16 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('equity', '0002_remove_series_company_alter_series_share_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='stockclass',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='series',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='series_set', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='share_type',
            field=models.CharField(blank=True, choices=[('COMMON', 'Common Stock'), ('PREFERRED', 'Preferred Stock')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='stockclass',
            unique_together={('company', 'name')},
        ),
    ]
