# Generated by Django 5.2.1 on 2025-07-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0002_equitygrant_common_shares_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equitygrant',
            name='nso_shares',
        ),
        migrations.AddField(
            model_name='equitygrant',
            name='nqo_shares',
            field=models.PositiveIntegerField(default=0, help_text='NQO share count'),
        ),
    ]
