# Generated by Django 5.2.1 on 2025-07-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0002_alter_series_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
