# Generated by Django 5.2.1 on 2025-07-21 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0003_remove_equitygrant_nso_shares_equitygrant_nqo_shares'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockclass',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='iso_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='nqo_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='num_shares',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='rsu_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='stock_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equity.stockclass'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='strike_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockclass',
            name='total_class_shares',
            field=models.PositiveIntegerField(),
        ),
    ]
