# Generated by Django 5.2.1 on 2025-07-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0003_alter_series_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='series',
            name='share_type',
            field=models.CharField(choices=[('ISO', 'Incentive Stock Option'), ('NQO', 'Non-Qualified Option'), ('RSU', 'Restricted Stock Unit'), ('COMMON', 'Common Stock'), ('PREFERRED', 'Preferred Stock')], max_length=100),
        ),
    ]
