# Generated by Django 5.2.4 on 2025-10-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0004_alter_series_options_alter_stockclass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
