# Generated by Django 5.2.1 on 2025-07-22 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_current_fmv_company_risk_free_rate_and_more'),
        ('equity', '0004_alter_stockclass_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitygrant',
            name='vesting_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Interval at which shares vest', max_length=10),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='iso_shares',
            field=models.PositiveIntegerField(default=0, help_text='ISO share count'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='nqo_shares',
            field=models.PositiveIntegerField(default=0, help_text='NQO share count'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='num_shares',
            field=models.PositiveIntegerField(help_text='Total shares allocated'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='rsu_shares',
            field=models.PositiveIntegerField(default=0, help_text='RSU share count'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='stock_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equity.stockclass'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockclass',
            name='total_class_shares',
            field=models.PositiveIntegerField(default=0, help_text='Shares this class may issue'),
        ),
        migrations.AlterUniqueTogether(
            name='stockclass',
            unique_together={('company', 'name')},
        ),
    ]
