# Generated by Django 5.2.1 on 2025-07-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0004_alter_series_name_alter_series_share_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='share_type',
            field=models.CharField(choices=[('COMMON', 'Common Stock'), ('PREFERRED', 'Preferred Stock')], max_length=100),
        ),
    ]
