# Generated by Django 5.2.4 on 2025-10-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0005_alter_stockclass_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockclass',
            name='share_type',
            field=models.CharField(choices=[('COMMON', 'Common Stock'), ('PREFERRED', 'Preferred Stock')], default=1, editable=False, max_length=16),
            preserve_default=False,
        ),
    ]
