# Generated by Django 5.2.1 on 2025-07-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0005_equitygrant_vesting_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equitygrant',
            name='cliff_months',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Months until first vest (cliff)'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='iso_shares',
            field=models.PositiveIntegerField(default=0, help_text='ISO shares count'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='nqo_shares',
            field=models.PositiveIntegerField(default=0, help_text='NQO shares count'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='rsu_shares',
            field=models.PositiveIntegerField(default=0, help_text='RSU shares count'),
        ),
    ]
