# Generated by Django 5.2.1 on 2025-07-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0006_alter_equitygrant_cliff_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equitygrant',
            name='cliff_months',
            field=models.PositiveIntegerField(default=0, help_text='Months since vesting started (auto-calculated)'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='iso_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='nqo_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='num_shares',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='rsu_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='stock_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equity.stockclass'),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='strike_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='vesting_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10),
        ),
    ]
