# Generated by Django 5.2.1 on 2025-07-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0007_alter_equitygrant_cliff_months_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockclass',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='equitygrant',
            name='cliff_months',
            field=models.PositiveIntegerField(default=0, help_text='Full months since vesting_start (auto-calculated on save)'),
        ),
        migrations.AlterField(
            model_name='stockclass',
            name='total_class_shares',
            field=models.PositiveIntegerField(),
        ),
    ]
